# Generated by Django 2.2.6 on 2019-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('quad', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
